### PR TITLE
Proves EVO-CR in its full generality, closing #2

### LINKED ISSUE #2: Evo-CR property is weaker than the original authors intended
Maniatis and Baker describe the key correctness condition "Theorem 3 (Evolutionary collision resistance of AASL membership proofs.)." somewhat informally.  We defined it formally as `evo-cr`, as described in out CPP2021 paper.

However, we have since noted that, a few paragraphs after their definition, Maniatis and Baker note that "A’s advancement path, the dark dashed line, does not necessarily go through element i" and similarly "B’s advancement path, the lighter dashed line, does not necessarily go through element i".

In contrast, our original definition of evo-cr included hypotheses " tgt ∈AP a₁" and "tgt ∈AP a₂", which (in the parlance of Maniatis and Baker) implies that A's and B's advancement proofs go through i.

Thus, the property we defined and proved is weaker (and much less useful) than Maniatis and Baker intended.

To address this issue, we are removing those superfluous hypotheses and proving the stronger property, as originally intended.

### PR DESCRIPTION
**Pull request by VictorCMiraldo**
- Proves `EVO-CR` without requiring that `tgt` belongs in `a_1` or `a_2`, as intended by Maniatis and Baker
- Refactors `Advancement.agda` into `DepRel.agda` and `Advancement.agda` to improve Agda's interactive performance
- closes #2

### CODE REVIEW

**Comment by mark-moir** [comment]
Thanks @VictorCMiraldo, looks good.  Just one thing: the refactoring of `Advancement.agda` broke `Concrete.agda` (so `./Script/run-everything.sh yes` fails).  It's an easy fix.   If you could take care of that, I'll gratefully accept the pull request.

**Comment by vcm-at-dfinity** [comment]
Sure, @mark-moir ! It's done.

**Comment by mark-moir** [comment]
@VictorCMiraldo, sorry for the inconvenience, but there are two small administrative items I forgot.

1. You didn't put `--signoff` on your last commit (see the [CONTRIBUTING guidelines](https://github.com/oracle/aaosl-agda/blob/main/CONTRIBUTING.md#contributing-code))
2. Because you introduced two new files, they don't have the necessary license/copyright header (the Contributing guidelines don't mention this, which I will address).  Can you please add a header something like the following (if/when someone internal changes these files, we'll then add Oracle to the copyright in addition to your name).

```
{- Formal verification of authenticated append-only skiplists in Agda, version 1.0.

   Copyright (c) 2021 Victor C Miraldo.
   Licensed under the Universal Permissive License v 1.0 as shown at https://opensource.oracle.com/licenses/upl
-}
```
Thanks!

**Comment by VictorCMiraldo** [comment]
@mark-moir Done both.

**Comment by mark-moir** [comment]
Great, thanks @VictorCMiraldo!  Approved and merged!

**Pull request merged**
